baseURL = "https://makkong.github.io/mkymnb.com/"
languageCode = "en-us"
theme = "sada"
disableKinds = ["taxonomy", "taxonomyTerm"]

publishDir = "docs"
canonifyurls = true

[params]
    name = "Makoto Noguchi website"
    title = "Makoto Nuguchi website"
    author = "Makoto Noguchi"
    description = "プロフィール"
    copyright = "Custom copyright message"
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Makoto Noguchi"
        photo = "./images/1111.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/mocochanman"
        title = "GitHub"
		

    # Education section
    [params.education]
        title = "学歴"

        [[params.education.list]]
        degree = "修士課程"
        college = "関西学院大学大学院 理工学研究科 情報科学専攻"
        dates = "2021.4 - *Present*"
        details = "研究課題：系列情報や地形図の多峰近似アルゴリズム、時系列データ解析"

        [[params.education.list]]
        degree = "学士"
        college = "関西学院大学 理工学部 情報科学科"
        dates = "2017 - 2021"
        details = "学士研究：ヒストグラムの最適な簡略化と数理モデルに関する研究"

    # Languages section
    [params.language]
        title = "言語"

        [[params.language.list]]
        language = "日本語"
        level = "母国語"
				
        [[params.language.list]]
        language = "英語"
        level = "TOEIC 700"

    # Interests section
    [params.hobbies]
        title = "趣味"

        [[params.hobbies.list]]
        interest = "サイクリング"
		
		[[params.hobbies.list]]
        interest = "映画・アニメ鑑賞"

        [[params.hobbies.list]]
        interest = "ゲーム(Switch、スマホ)"

    [params.aboutme]
        description = "Tコンピュータサイエンスを専攻している修士課程１年生。主な研究テーマは、計算幾何学アルゴリズム、深層学習アルゴリズム。"

    # Experiences section
    [params.experiences]
        title = "職歴"

        [[params.jobs.list]]
        position = "Jアルバイト"
        dates = "2017.5 - *Present*"
		link = "https://www.kyoshin.co.jp/s1/schooldetail/269/"
        company = "京進スクールワン - 個別指導塾"
        details = "小学生から高校３年生までを幅広く担当。担当科目は国語・数学・英語全般、化学・物理・生物基礎、地理、情報。　更に、業務形態の改善や慢性的な退勤時間問題の解消にも従事"

        [[params.jobs.list]]
        dates = "2021.4 - *Present*"
        company = "研究補助及びTeaching Assistant"
        details = "研究室におけるデータ収集やソフトウェア管理、実習系授業の採点担当"

    # Projects section
    [params.projects]
        title = "インターンシップ、イベント、勉強会"

        [[params.projects.list]]
        details = "・在籍中の大学院にて、MLに関する書籍の輪読会に参加中・2019.8 日本IBM 大阪支社にて、データサイエンススペシャリストや技術理事の方との座談会に参加"

    # Skills section
    [params.skills]
        title = "スキル"

        [[params.skills.list]]
        skill = "Python：１〜２年"
        details = "・研究時のプログラムや機械学習全般に使用"
                
        [[params.skills.list]]
        skill = "C：２〜３年"
        details = "大学3年時に、情報処理学会東北支部設立30周年記念プログラミングコンテストにおけるリンゴキャッチ競争という課題について、プログラムを作成"
		
        [[params.skills.list]]
        skill = "C++：０〜１年"
        details = "Aizu Online Judgeを用いたデータ構造とアルゴリズムの学習時に使用"

        [[params.skills.list]]
        skill = "HTML/CSS：０〜１年"
        details = "研究室のHPや当ウェブサイトの作成に使用"